/*!
Chosen, a Select Box Enhancer for jQuery and Prototype
by Patrick Filler for Harvest, http://getharvest.com

Version 1.4.2
Full source at https://github.com/harvesthq/chosen
Copyright (c) 2011-2015 Harvest http://getharvest.com

MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
This file is generated by `grunt build`, do not edit it by hand.
*/


(function() {
  var $, AbstractChosen, Chosen, SelectParser, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SelectParser = (function() {
    function SelectParser() {
      this.options_index = 0;
      this.parsed = [];
    }

    SelectParser.prototype.add_node = function(child) {
      if (child.nodeName.toUpperCase() === "OPTGROUP") {
        return this.add_group(child);
      } else {
        return this.add_option(child);
      }
    };

    SelectParser.prototype.add_group = function(group) {

      var group_position, option, _i, _len, _ref, _results;
      group_position = this.parsed.length;
      this.parsed.push({
        array_index: group_position,
        group: true,
        label: this.escapeExpression(group.label),
        title: group.title ? group.title : void 0,
        children: 0,
        disabled: group.disabled,
        classes: group.className
      });
      _ref = group.childNodes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        _results.push(this.add_option(option, group_position, group.disabled));
      }
      return _results;
    };

    SelectParser.prototype.add_option = function(option, group_position, group_disabled) {
      if (option.nodeName.toUpperCase() === "OPTION") {
        if (option.text !== "") {
          if (group_position != null) {
            this.parsed[group_position].children += 1;
          }
          this.parsed.push({
            array_index: this.parsed.length,
            options_index: this.options_index,
            value: option.value,
            text: option.text,
            html: option.innerHTML,
            title: option.title ? option.title : void 0,
            selected: option.selected,
            disabled: group_disabled === true ? group_disabled : option.disabled,
            group_array_index: group_position,
            group_label: group_position != null ? this.parsed[group_position].label : null,
            classes: option.className,
            style: option.style.cssText
          });
        } else {
          this.parsed.push({
            array_index: this.parsed.length,
            options_index: this.options_index,
            empty: true
          });
        }
        return this.options_index += 1;
      }
    };

    SelectParser.prototype.escapeExpression = function(text) {
      var map, unsafe_chars;
      if ((text == null) || text === false) {
        return "";
      }
      if (!/[\&\<\>\"\'\`]/.test(text)) {
        return text;
      }
      map = {
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#x27;",
        "`": "&#x60;"
      };
      unsafe_chars = /&(?!\w+;)|[\<\>\"\'\`]/g;
      return text.replace(unsafe_chars, function(chr) {
        return map[chr] || "&amp;";
      });
    };

    return SelectParser;

  })();

  SelectParser.select_to_array = function(select) {
    var child, parser, _i, _len, _ref;
    parser = new SelectParser();
    _ref = select.childNodes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      parser.add_node(child);
    }
    return parser.parsed;
  };


  AbstractChosen = (function() {
    function AbstractChosen(form_field, options) {
      this.form_field = form_field;
      this.options = options != null ? options : {};
      this.current_value =  this.options.default_value || ""; //远程加载时候无法通过value 保存值  暂存当前选中值 和初始化值 select
      if (!AbstractChosen.browser_is_supported()) {
        return ;
      }
      this.is_multiple = this.form_field.multiple;

      this.init = function () {
        this.set_default_text();
        this.set_default_values();
        this.setup();
        this.set_up_html();
        this.register_observers();
        this.on_ready();
      }
      this.remote_data = null; // 只存数组
      // 获取远程数据
      if(this.options.url) {
        var that = this;
        this.get_data().then(function () {
          that.reset_select_options();
          that.init();
          //绑定分页功能
          that.infiniteScroll = new InfiniteScroll(that);
        });
      } else {
        this.init();
      }

    }

    // 重建 select option选项 方法
    AbstractChosen.prototype.reset_select_options = function (isLoad) {
      var that = this;
        // clear
      $(that.form_field).html("");
      // if(this.container.length > 0) {
      //     this.container.remove();
      // };
      $(that.form_field).append("<option  value=''>-请选择-</option>");
      if(!that.options.field_text || !that.options.field_id) {
          console.warn("未设置选项的id,text对应的字段名");
      }
      try { 
        if(that.options.field_text && that.options.field_text.indexOf(",") >= 0) {
          var subindex = that.options.field_text.indexOf(",");
          var textarr = that.options.field_text.split(",");
        }
      } catch (e) {
         throw e;
      }
      if(this.remote_data instanceof Array) {
        $.each(this.remote_data,function (idx) {
          var $item
          if(textarr) {
            $item= $("<option  value='" + this[that.options.field_id] +"' >" +  this[textarr[0]] + "-" + this[textarr[1]] + "</option>");
            $item.data('data',this);
          } else {
            $item= $("<option  value='" + this[that.options.field_id] +"' >" +  this[that.options.field_text] + "</option>");
            $item.data('data',this);

          }
          $(that.form_field).append($item);
        })
      } else {
          console.error(this.remote_data,"不是数组类型")
      }
      //填充 select 之后触发 选中方法
       if(!isLoad) { // 分页 加载方法重置 并不需要触发
           that.set_value(that.current_value);
       }

    }





    AbstractChosen.prototype.set_default_values = function() {
      var _this = this;
      this.click_test_action = function(evt) {
        return _this.test_active_click(evt);
      };
      this.activate_action = function(evt) {
        return _this.activate_field(evt);
      };
      this.active_field = false;
      this.mouse_on_container = false;
      this.results_showing = false;
      this.result_highlighted = null;
      this.allow_single_deselect = (this.options.allow_single_deselect != null) && (this.form_field.options[0] != null) && this.form_field.options[0].text === "" ? this.options.allow_single_deselect : false;
      this.disable_search_threshold = this.options.disable_search_threshold || 0;
      this.disable_search = this.options.disable_search || false;
      this.enable_split_word_search = this.options.enable_split_word_search != null ? this.options.enable_split_word_search : true;
      this.group_search = this.options.group_search != null ? this.options.group_search : true;
      this.search_contains = this.options.search_contains || true; // false 从头搜索
      this.single_backstroke_delete = this.options.single_backstroke_delete != null ? this.options.single_backstroke_delete : true;
      this.max_selected_options = this.options.max_selected_options || Infinity;
      this.inherit_select_classes = this.options.inherit_select_classes || false;
      this.display_selected_options = this.options.display_selected_options != null ? this.options.display_selected_options : true;
      this.display_disabled_options = this.options.display_disabled_options != null ? this.options.display_disabled_options : true;
      return this.include_group_label_in_selected = this.options.include_group_label_in_selected || false;
    };

    AbstractChosen.prototype.set_default_text = function() {
      if (this.form_field.getAttribute("data-placeholder")) {
        this.default_text = this.form_field.getAttribute("data-placeholder");
      } else if (this.is_multiple) {
        this.default_text = this.options.placeholder_text_multiple || this.options.placeholder_text || AbstractChosen.default_multiple_text;
      } else {
        this.default_text = this.options.placeholder_text_single || this.options.placeholder_text || AbstractChosen.default_single_text;
      }
      return this.results_none_found = this.form_field.getAttribute("data-no_results_text") || this.options.no_results_text || AbstractChosen.default_no_result_text;
    };

    AbstractChosen.prototype.choice_label = function(item) {
      if (this.include_group_label_in_selected && (item.group_label != null)) {
        return "<b class='group-name'>" + item.group_label + "</b>" + item.html;
      } else {
        return item.html;
      }
    };

    AbstractChosen.prototype.mouse_enter = function() {
      return this.mouse_on_container = true;
    };

    AbstractChosen.prototype.mouse_leave = function() {
      return this.mouse_on_container = false;
    };

    AbstractChosen.prototype.input_focus = function(evt) {
      var _this = this;
      if (this.is_multiple) {
        if (!this.active_field) {
          return setTimeout((function() {
            return _this.container_mousedown();
          }), 50);
        }
      } else {
        if (!this.active_field) {
          return this.activate_field();
        }
      }
    };

    AbstractChosen.prototype.input_blur = function(evt) {
      var _this = this;
      if (!this.mouse_on_container) {
        this.active_field = false;
        return setTimeout((function() {
          return _this.blur_test();
        }), 100);
      }
    };
    // 根据 .results_data  构建 ul li 的字符串
    AbstractChosen.prototype.results_option_build = function(options) {
      var content, data, _i, _len, _ref;
      content = '';
      _ref = this.results_data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        data = _ref[_i];
        if (data.group) {
          content += this.result_add_group(data);
        } else {
          content += this.result_add_option(data);
        }
        if (options != null ? options.first : void 0) {
          if (data.selected && this.is_multiple) {
            this.choice_build(data);
          } else if (data.selected && !this.is_multiple) {
            this.single_set_selected_text(this.choice_label(data));
          }
        }
      }
      return content;
    };

    AbstractChosen.prototype.result_add_option = function(option) {
      var classes, option_el;
      if (!option.search_match) {
        return '';
      }
      if (!this.include_option_in_results(option)) {
        return '';
      }
      classes = [];
      if (!option.disabled && !(option.selected && this.is_multiple)) {
        classes.push("active-result");
      }
      if (option.disabled && !(option.selected && this.is_multiple)) {
        classes.push("disabled-result");
      }
      if (option.selected) {
        classes.push("result-selected");
      }
      if (option.group_array_index != null) {
        classes.push("group-option");
      }
      if (option.classes !== "") {
        classes.push(option.classes);
      }
      option_el = document.createElement("li");
      option_el.className = classes.join(" ");
      option_el.style.cssText = option.style;
      option_el.setAttribute("data-option-array-index", option.array_index);
      option_el.innerHTML = option.search_text;
      if (option.title) {
        option_el.title = option.title;
      }
      return this.outerHTML(option_el);
    };

    AbstractChosen.prototype.result_add_group = function(group) {
      var classes, group_el;
      if (!(group.search_match || group.group_match)) {
        return '';
      }
      if (!(group.active_options > 0)) {
        return '';
      }
      classes = [];
      classes.push("group-result");
      if (group.classes) {
        classes.push(group.classes);
      }
      group_el = document.createElement("li");
      group_el.className = classes.join(" ");
      group_el.innerHTML = group.search_text;
      if (group.title) {
        group_el.title = group.title;
      }
      return this.outerHTML(group_el);
    };


    // 根据 select option  初始化  ul li
    AbstractChosen.prototype.results_update_field = function() {
      this.set_default_text();
      if (!this.is_multiple) {
        this.results_reset_cleanup();
      }
      this.result_clear_highlight();
      this.results_build();
      if (this.results_showing) {
        return this.winnow_results();
      }
    };

    AbstractChosen.prototype.reset_single_select_options = function() {
      var result, _i, _len, _ref, _results;
      _ref = this.results_data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        result = _ref[_i];
        if (result.selected) {
          _results.push(result.selected = false);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    AbstractChosen.prototype.results_toggle = function() {
      if (this.results_showing) {
        return this.results_hide();
      } else {
        return this.results_show();
      }
    };
    // 搜索 方法
    AbstractChosen.prototype.results_search = function(evt) {
      //增加远程搜索功能
      // 1.先搜索本地是否存在 同名的 选项
      //  2.再查询远程是否存在
      // if(this.options.url) {
      // }
      var ret;
      if (this.results_showing) {
        ret= this.winnow_results();
      } else {
        ret= this.results_show();
      }

      if(this.options.url) {
        if(searchTimeout) {
          clearTimeout(searchTimeout);
          searchTimeout = null;
        }
        var that = this;
        searchTimeout = setTimeout(function () {
          that.remote_search(); // ret 是promise 不知道会有什么影响
        },400);
      }
      return ret
    };

    /**
    * 3 远程搜索
    *  3.1  查询结果写入 select 中  done
     * 3.2  查询结果覆盖到 ul li 中 done
     * 3.3 避免频繁发起查询 设置间隔
     * 3.4 原始 search 功能只能从第一个字符开始匹配 返回搜索结果 需要替换一下匹配规则
     * 3.5 分页数据 在关闭之后 清理掉 重置当前页码
     * 3.6
     *
    */
    //远程搜索功能
    var searchTimeout ;
    // 暂时没有建队列来处理  输入搜索 看谁又这么快的操作数 再加

    AbstractChosen.prototype.remote_search = function () {
      var searchText = this.get_search_text();
      if (!this.options.param) {
        this.options.param = { q :  searchText }
      } else {
        this.options.param.q  = searchText;
      }
      var that = this;

      this.infiniteScroll.setPage(1); // 必须要重置分页 不然 携带了分页数据 查询失败
      //搜索结果超过30 条可能被分页  删除 rows 属性 clear search 再回设置
      // if(that.infiniteScroll) {
      //   that.infiniteScroll.currentPage = 1;
      // }

      this.get_data().then(function () {
        if(that.remote_data < 1) {
          return "啥也没搜到"
        }
        // 分页 之后远程搜索 页码 问题
        // 搜索关键字被清空
        that.reset_select_options(true); //这里 重写组装  select
        that.results_data = that.remote_data;
        that.results_build(true); //这里 search_math 为 undefine 导致返回的 context 为空 并不能成功 组装和映射 ul li  唯一的作用是 重写 that.chosen.results_data
        that.winnow_results(); //构造新的 ulli 准备数据 和筛选
      })
    };
    // 清理之前远程搜索的结果
    AbstractChosen.prototype.clear_remote_search = function () {
      var searchText = this.get_search_text();
      var that = this;
      var promise;
      // this.infiniteScroll.bind();
      // debugger; //清除 remote 结果要 保存 选中的值
      if(this.options.url && this.options.param && this.options.param.q) {
        // this.options.param.page = 1;   //分页
        // this.infiniteScroll.currentPage = 1;
        this.infiniteScroll.setPage(1);  // 考虑一下这里 互相依赖 如何分离
        var cacheQ = this.options.param.q;
        this.options.param.q = null;


        var catcheValue;
        if(this.form_field.value) {
           // 搜索且选中
          catcheValue = this.form_field.value;

        }

        promise = this.get_data();
        promise.then(function () {
          that.reset_select_options(true); //这里 重写组装  select  true 标示不触发 change
          that.results_data = that.remote_data;
          that.results_build(true);   //这里 search_math 为 undefine 导致返回的 context 为空 并不能成功 组装和映射 ul li  唯一的作用是 重写 that.chosen.results_data
        });
      }
      return promise;
    }



    //本地比较搜索结果  组装新下拉列表 :只能从最左边开始匹配
    AbstractChosen.prototype.winnow_results = function(build_flag) { // build_flag
      var escapedSearchText, option, regex, results, results_group, searchText, startpos, text, zregex, _i, _len, _ref;
      this.no_results_clear();
      results = 0;
      searchText = this.get_search_text();
      escapedSearchText = searchText.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
      zregex = new RegExp(escapedSearchText, 'i');
      regex = this.get_search_regex(escapedSearchText);
      _ref = this.results_data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        option.search_match = false;
        results_group = null;
        if (this.include_option_in_results(option)) {
          if (option.group) {
            option.group_match = false;
            option.active_options = 0;
          }
          if ((option.group_array_index != null) && this.results_data[option.group_array_index]) {
            results_group = this.results_data[option.group_array_index];
            if (results_group.active_options === 0 && results_group.search_match) {
              results += 1;
            }
            results_group.active_options += 1;
          }
          option.search_text = option.group ? option.label : option.html;
          if (!(option.group && !this.group_search)) {
            option.search_match = this.search_string_match(option.search_text, regex);
            if (option.search_match && !option.group) {
              results += 1;
            }
            if (option.search_match) {
              if (searchText.length) {
                startpos = option.search_text.search(zregex);
                text = option.search_text.substr(0, startpos + searchText.length) + '</em>' + option.search_text.substr(startpos + searchText.length);
                option.search_text = text.substr(0, startpos) + '<em>' + text.substr(startpos);
              }
              if (results_group != null) {
                results_group.group_match = true;
              }
            } else if ((option.group_array_index != null) && this.results_data[option.group_array_index].search_match) {
              option.search_match = true;
            }
          }
        }
      }

      if(build_flag) { return false; }
      //this.result_clear_highlight();
      if (results < 1 && searchText.length) {
        this.update_results_content("");
        return this.no_results(searchText);
      } else {
        // 更新查询结果返回的新列表
        this.update_results_content(this.results_option_build());
        return this.winnow_results_set_highlight();
      }
    };

    AbstractChosen.prototype.get_search_regex = function(escaped_search_string) {
      var regex_anchor;
      regex_anchor = this.search_contains ? "" : "^";
      return new RegExp(regex_anchor + escaped_search_string, 'i');
    };

    AbstractChosen.prototype.search_string_match = function(search_string, regex) {
      var part, parts, _i, _len;
      if (regex.test(search_string)) {
        return true;
      } else if (this.enable_split_word_search && (search_string.indexOf(" ") >= 0 || search_string.indexOf("[") === 0)) {
        parts = search_string.replace(/\[|\]/g, "").split(" ");
        if (parts.length) {
          for (_i = 0, _len = parts.length; _i < _len; _i++) {
            part = parts[_i];
            if (regex.test(part)) {
              return true;
            }
          }
        }
      }
    };

    AbstractChosen.prototype.choices_count = function() {
      var option, _i, _len, _ref;
      if (this.selected_option_count != null) {
        return this.selected_option_count;
      }
      this.selected_option_count = 0;
      _ref = this.form_field.options;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        if (option.selected) {
          this.selected_option_count += 1;
        }
      }
      return this.selected_option_count;
    };

    AbstractChosen.prototype.choices_click = function(evt) {
      evt.preventDefault();
      if (!(this.results_showing || this.is_disabled)) {
        return this.results_show();
      }
    };

    AbstractChosen.prototype.keyup_checker = function(evt) {
      var stroke, _ref;
      stroke = (_ref = evt.which) != null ? _ref : evt.keyCode;
      this.search_field_scale();
      switch (stroke) {
        case 8: // BackSpace
          if (this.is_multiple && this.backstroke_length < 1 && this.choices_count() > 0) {
            return this.keydown_backstroke();
          } else if (!this.pending_backstroke) {
            this.result_clear_highlight();
            return this.results_search();
          }
          break;
        case 13: // Enter
          evt.preventDefault();
          if (this.results_showing) {
            return this.result_select(evt);
          }
          break;
        case 27: // Escape
          if (this.results_showing) {
            this.results_hide();
          }
          return true;
        case 9:
        case 38:
        case 40:
        case 16:
        case 91:
        case 17:
          break;
        default:
          return this.results_search();
      }
    };

    AbstractChosen.prototype.clipboard_event_checker = function(evt) {
      var _this = this;
      return setTimeout((function() {
        return _this.results_search();
      }), 50);
    };

    AbstractChosen.prototype.container_width = function() {
      if (this.options.width != null) {
        return this.options.width;
      } else {
        if($(this.form_field).is(":hidden") || this.form_field.offsetWidth < 200 ) { // 被隐藏  或者 还未初始化 option 选项
           return "200px"; // 没有设置 宽度且select 已经隐藏
        }
        return "" + this.form_field.offsetWidth + "px";
      }
    };

    AbstractChosen.prototype.include_option_in_results = function(option) {
      if (this.is_multiple && (!this.display_selected_options && option.selected)) {
        return false;
      }
      if (!this.display_disabled_options && option.disabled) {
        return false;
      }
      if (option.empty) {
        return false;
      }
      return true;
    };

    AbstractChosen.prototype.search_results_touchstart = function(evt) {
      this.touch_started = true;
      return this.search_results_mouseover(evt);
    };

    AbstractChosen.prototype.search_results_touchmove = function(evt) {
      this.touch_started = false;
      return this.search_results_mouseout(evt);
    };

    AbstractChosen.prototype.search_results_touchend = function(evt) {
      if (this.touch_started) {
        return this.search_results_mouseup(evt);
      }
    };

    AbstractChosen.prototype.outerHTML = function(element) {
      var tmp;
      if (element.outerHTML) {
        return element.outerHTML;
      }
      tmp = document.createElement("div");
      tmp.appendChild(element);
      return tmp.innerHTML;
    };

    AbstractChosen.browser_is_supported = function() {
      if (window.navigator.appName === "Microsoft Internet Explorer") {
        return document.documentMode >= 8;
      }
      if (/iP(od|hone)/i.test(window.navigator.userAgent)) {
        return false;
      }
      if (/Android/i.test(window.navigator.userAgent)) {
        if (/Mobile/i.test(window.navigator.userAgent)) {
          return false;
        }
      }
      return true;
    };

    AbstractChosen.default_multiple_text = "-请选择-";

    AbstractChosen.default_single_text = "-请选择-";

    AbstractChosen.default_no_result_text = "No results match";
    /**
    * 显示隐藏 加载提示框
    *
    *
    */
    AbstractChosen.prototype.showLoadingMore = function () {
      if(!this.container) return "还未初始化";
      if(!this.isloading) {
        var $more = $("<div class='chosen-moreloading' />");
        var $chosendrop = this.container.find(".chosen-drop");
        $chosendrop.prepend($more);
      }
      this.isloading = true;
    };
    AbstractChosen.prototype.hideLoadingMore = function () {
      if(!this.container) return "还未初始化";
      this.container.find(".chosen-moreloading").remove();
      this.isloading = false;
    };


    return AbstractChosen;

  })();

  $ = jQuery;

  $.fn.extend({
    chosen: function(options) {
      if (!AbstractChosen.browser_is_supported()) {
        return this;
      }
      return this.each(function(input_field) {
        var $this, chosen;
        $this = $(this);
        chosen = $this.data('chosen');
        if (options === 'destroy' && chosen instanceof Chosen) {
          chosen.destroy();
        } else if (!(chosen instanceof Chosen)) {
          $this.data('chosen', new Chosen(this, options)); // 可以从 dom  获取到整个实例
        }
      });
    }
  });

  Chosen = (function(_super) {
    __extends(Chosen, _super);

    function Chosen() {
      _ref = Chosen.__super__.constructor.apply(this, arguments);
      return _ref;
    }


    Chosen.prototype.setup = function() {
      this.form_field_jq = $(this.form_field);
      this.current_selectedIndex = this.form_field.selectedIndex;
      return this.is_rtl = this.form_field_jq.hasClass("chosen-rtl");
    };
    Chosen.prototype.css_props = function () {
      var container_classes, container_props;
      container_classes = ["chosen-container"];
      container_classes.push("chosen-container-" + (this.is_multiple ? "multi" : "single"));
      if (this.inherit_select_classes && this.form_field.className) {
        container_classes.push(this.form_field.className);
      }
      if (this.is_rtl) {
        container_classes.push("chosen-rtl");
      }
      container_props = {
        'class': container_classes.join(' '),
        'style': "width: " + (this.container_width()) + ";",
        'title': this.form_field.title
      };
      return container_props;
    }


    // 构造 ul 的入口
    Chosen.prototype.set_up_html = function() {

      // var container_classes, container_props;
      // container_classes = ["chosen-container"];
      // container_classes.push("chosen-container-" + (this.is_multiple ? "multi" : "single"));
      // if (this.inherit_select_classes && this.form_field.className) {
      //   container_classes.push(this.form_field.className);
      // }
      // if (this.is_rtl) {
      //   container_classes.push("chosen-rtl");
      // }
      // container_props = {
      //   'class': container_classes.join(' '),
      //   'style': "width: " + (this.container_width()) + ";",
      //   'title': this.form_field.title
      // };
      var container_props = this.css_props();
      if (this.form_field.id.length) {
        container_props.id = this.form_field.id.replace(/[^\w]/g, '_') + "_chosen";
      }
      this.container = $("<div />", container_props);
      if (this.is_multiple) {
        this.container.html('<ul class="chosen-choices"><li class="search-field"><input type="text" value="' + this.default_text + '" class="default" autocomplete="off" style="width:25px;" /></li></ul><div class="chosen-drop"><ul class="chosen-results"></ul></div>');
      } else {
        this.container.html('<a class="chosen-single chosen-default" tabindex="-1"><span>' + this.default_text + '</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off" /></div><ul class="chosen-results"></ul></div>');
      }
      // 做之前 hide 的替代方法
      this.form_field_jq.width(0);
      this.form_field_jq.height(0);
      this.form_field_jq[0].style.visibility="hidden";
      this.form_field_jq.before(this.container); //测试用 ！ 隐藏时获取 宽度存在问题   .hide()   by li
      this.dropdown = this.container.find('div.chosen-drop').first();
      this.search_field = this.container.find('input').first();
      this.search_results = this.container.find('ul.chosen-results').first();
      this.search_field_scale();
      this.search_no_results = this.container.find('li.no-results').first();
      if (this.is_multiple) {
        this.search_choices = this.container.find('ul.chosen-choices').first();
        this.search_container = this.container.find('li.search-field').first();
      } else {
        this.search_container = this.container.find('div.chosen-search').first();
        this.selected_item = this.container.find('.chosen-single').first();
      }
      this.results_build();
      this.set_tab_index();
      return this.set_label_behavior();
    };

    Chosen.prototype.on_ready = function() {
      return this.form_field_jq.trigger("chosen:ready", {
        chosen: this
      });
    };
    // add li 注册点击下拉列表事件 回调函数的地方
    //Chosen.prototype.on_select = function() {
    // // if(typeof callback == "function") callback();
    //};

    Chosen.prototype.register_observers = function() {
      var _this = this;
      this.container.bind('touchstart.chosen', function(evt) {
        _this.container_mousedown(evt);
        return evt.preventDefault();
      });
      this.container.bind('touchend.chosen', function(evt) {
        _this.container_mouseup(evt);
        return evt.preventDefault();
      });
      this.container.bind('mousedown.chosen', function(evt) {
        _this.container_mousedown(evt);
      });
      this.container.bind('mouseup.chosen', function(evt) {
        _this.container_mouseup(evt);
      });
      this.container.bind('mouseenter.chosen', function(evt) {
        _this.mouse_enter(evt);
      });
      this.container.bind('mouseleave.chosen', function(evt) {
        _this.mouse_leave(evt);
      });
      this.search_results.bind('mouseup.chosen', function(evt) {
        _this.search_results_mouseup(evt);
      });
      this.search_results.bind('mouseover.chosen', function(evt) {
        _this.search_results_mouseover(evt);
      });
      this.search_results.bind('mouseout.chosen', function(evt) {
        _this.search_results_mouseout(evt);
      });
      this.search_results.bind('mousewheel.chosen DOMMouseScroll.chosen', function(evt) {
        _this.search_results_mousewheel(evt);
      });
      this.search_results.bind('touchstart.chosen', function(evt) {
        _this.search_results_touchstart(evt);
      });
      this.search_results.bind('touchmove.chosen', function(evt) {
        _this.search_results_touchmove(evt);
      });
      this.search_results.bind('touchend.chosen', function(evt) {
        _this.search_results_touchend(evt);
      });
      this.form_field_jq.bind("chosen:updated.chosen", function(evt) {
        _this.results_update_field(evt);
      });
      this.form_field_jq.bind("chosen:activate.chosen", function(evt) {
        _this.activate_field(evt);
      });
      // add by li
      this.search_results.bind("click", function(evt) {
         //console.log(_this.on_select);
       if( typeof _this.options.onselect == "function" ) _this.options.onselect();
      });

      this.form_field_jq.bind("chosen:open.chosen", function(evt) {
        _this.container_mousedown(evt);
      });
      this.form_field_jq.bind("chosen:close.chosen", function(evt) {
        _this.input_blur(evt);
      });
      this.search_field.bind('blur.chosen', function(evt) {
        _this.input_blur(evt);
      });
      this.search_field.bind('keyup.chosen', function(evt) {
        _this.keyup_checker(evt);
      });
      this.search_field.bind('keydown.chosen', function(evt) {
        _this.keydown_checker(evt);
      });
      this.search_field.bind('focus.chosen', function(evt) {
        _this.input_focus(evt);
      });
      this.search_field.bind('cut.chosen', function(evt) {
        _this.clipboard_event_checker(evt);
      });
      this.search_field.bind('paste.chosen', function(evt) {
        _this.clipboard_event_checker(evt);
      });
      if (this.is_multiple) {
        return this.search_choices.bind('click.chosen', function(evt) {
          _this.choices_click(evt);
        });
      } else {
        return this.container.bind('click.chosen', function(evt) {

          evt.preventDefault();
        });
      }
    };

    Chosen.prototype.destroy = function() {
      $(this.container[0].ownerDocument).unbind("click.chosen", this.click_test_action);
      if (this.search_field[0].tabIndex) {
        this.form_field_jq[0].tabIndex = this.search_field[0].tabIndex;
      }
      this.container.remove();
      this.form_field_jq.removeData('chosen');
      return this.form_field_jq.show();
    };

    Chosen.prototype.search_field_disabled = function() {
      this.is_disabled = this.form_field_jq[0].disabled;
      if (this.is_disabled) {
        this.container.addClass('chosen-disabled');
        this.search_field[0].disabled = true;
        if (!this.is_multiple) {
          this.selected_item.unbind("focus.chosen", this.activate_action);
        }
        return this.close_field();
      } else {
        this.container.removeClass('chosen-disabled');
        this.search_field[0].disabled = false;
        if (!this.is_multiple) {
          return this.selected_item.bind("focus.chosen", this.activate_action);
        }
      }
    };

    Chosen.prototype.container_mousedown = function(evt) {
      if (!this.is_disabled) {
        if (evt && evt.type === "mousedown" && !this.results_showing) {
          evt.preventDefault();
        }
        if (!((evt != null) && ($(evt.target)).hasClass("search-choice-close"))) {
          if (!this.active_field) {
            if (this.is_multiple) {
              this.search_field.val("");
            }
            $(this.container[0].ownerDocument).bind('click.chosen', this.click_test_action);
            this.results_show();
          } else if (!this.is_multiple && evt && (($(evt.target)[0] === this.selected_item[0]) || $(evt.target).parents("a.chosen-single").length)) {
            evt.preventDefault();
            this.results_toggle();
          }
          return this.activate_field();
        }
      }
    };

    Chosen.prototype.container_mouseup = function(evt) {
      if (evt.target.nodeName === "ABBR" && !this.is_disabled) {
        return this.results_reset(evt);
      }
    };

    Chosen.prototype.search_results_mousewheel = function(evt) {
      var delta;
      if (evt.originalEvent) {
        delta = evt.originalEvent.deltaY || -evt.originalEvent.wheelDelta || evt.originalEvent.detail;
      }
      if (delta != null) {
        evt.preventDefault();
        if (evt.type === 'DOMMouseScroll') {
          delta = delta * 40;
        }
        return this.search_results.scrollTop(delta + this.search_results.scrollTop());
      }
    };

    Chosen.prototype.blur_test = function(evt) {
      if (!this.active_field && this.container.hasClass("chosen-container-active")) {
        return this.close_field();
      }
    };

    Chosen.prototype.close_field = function() {
      $(this.container[0].ownerDocument).unbind("click.chosen", this.click_test_action);
      this.active_field = false;
      this.results_hide();
      this.container.removeClass("chosen-container-active");
      this.clear_backstroke();
      this.show_search_field_default();
      //由于没有 url 参数的 chosen 是静态的 并不会重置  select 所以这里增加一个 如果是动态创建就重置的方法

     // this.clear_remote_search();  // 可以注释 清理远程搜索 检查分页和搜素功能问题
      return this.search_field_scale();
    };

    Chosen.prototype.activate_field = function() {
      this.container.addClass("chosen-container-active");
      this.active_field = true;
      this.search_field.val(this.search_field.val());
      return this.search_field.focus();
    };

    Chosen.prototype.test_active_click = function(evt) {
      var active_container;
      active_container = $(evt.target).closest('.chosen-container');
      if (active_container.length && this.container[0] === active_container[0]) {
        return this.active_field = true;
      } else {
        return this.close_field();
      }
    };
    // 组装 chosen  ul  工作
    Chosen.prototype.results_build = function(isRemoteBuild) {
      this.parsing = true;
      this.selected_option_count = null;
      this.results_data = SelectParser.select_to_array(this.form_field);
      if (this.is_multiple) {
        this.search_choices.find("li.search-choice").remove();
      } else if (!this.is_multiple) {

        if(!isRemoteBuild) { // 如果是远程搜索 搜索完就 清除掉 text 会有点不好
          this.single_set_selected_text();
        }
        if (this.disable_search || this.form_field.options.length <= this.disable_search_threshold) {
          this.search_field[0].readOnly = true;
          this.container.addClass("chosen-container-single-nosearch");
        } else {
          this.search_field[0].readOnly = false;
          this.container.removeClass("chosen-container-single-nosearch");
        }
      }

      if(!isRemoteBuild) {
        this.update_results_content(this.results_option_build({
          first: true
        }));
      } else {
        this.update_results_content(this.results_option_build());
      }

      this.search_field_disabled();
      if(!isRemoteBuild) {
        this.show_search_field_default();
      }
      this.search_field_scale();
      return this.parsing = false;
    };

    Chosen.prototype.result_do_highlight = function(el) {

      var high_bottom, high_top, maxHeight, visible_bottom, visible_top;
      if (el.length) {
        this.result_clear_highlight();
        this.result_highlight = el;
        this.result_highlight.addClass("highlighted");
        maxHeight = parseInt(this.search_results.css("maxHeight"), 10);
        visible_top = this.search_results.scrollTop();
        visible_bottom = maxHeight + visible_top;
        high_top = this.result_highlight.position().top + this.search_results.scrollTop();
        high_bottom = high_top + this.result_highlight.outerHeight();
        if (high_bottom >= visible_bottom) {
          return this.search_results.scrollTop((high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);
        } else if (high_top < visible_top) {
          return this.search_results.scrollTop(high_top);
        }
      }
    };

    Chosen.prototype.result_clear_highlight = function() {
      if (this.result_highlight) {
        this.result_highlight.removeClass("highlighted");
      }
      return this.result_highlight = null;
    };

    Chosen.prototype.results_show = function() {
      if (this.is_multiple && this.max_selected_options <= this.choices_count()) {
        this.form_field_jq.trigger("chosen:maxselected", {
          chosen: this
        });
        return false;
      }
      this.container.addClass("chosen-with-drop");
      this.results_showing = true;
      this.search_field.focus();
      this.search_field.val(this.search_field.val());
      this.winnow_results();  // 会清理 ul li
      return this.form_field_jq.trigger("chosen:showing_dropdown", {
        chosen: this
      });
    };

    Chosen.prototype.update_results_content = function(content) {
      return this.search_results.html(content);
    };

    Chosen.prototype.results_hide = function() {
      if (this.results_showing) {
        this.result_clear_highlight();
        this.container.removeClass("chosen-with-drop");
        this.form_field_jq.trigger("chosen:hiding_dropdown", {
          chosen: this
        });
      }
      return this.results_showing = false;
    };

    Chosen.prototype.set_tab_index = function(el) {
      var ti;
      if (this.form_field.tabIndex) {
        ti = this.form_field.tabIndex;
        this.form_field.tabIndex = -1;
        return this.search_field[0].tabIndex = ti;
      }
    };

    Chosen.prototype.set_label_behavior = function() {
      var _this = this;
      this.form_field_label = this.form_field_jq.parents("label");
      if (!this.form_field_label.length && this.form_field.id.length) {
        this.form_field_label = $("label[for='" + this.form_field.id + "']");
      }
      if (this.form_field_label.length > 0) {
        return this.form_field_label.bind('click.chosen', function(evt) {
          if (_this.is_multiple) {
            return _this.container_mousedown(evt);
          } else {
            return _this.activate_field();
          }
        });
      }
    };

    Chosen.prototype.show_search_field_default = function() {
      var searchText = this.get_search_text();
      if (this.is_multiple && this.choices_count() < 1 && !this.active_field) {
        this.search_field.val(this.default_text);
        return this.search_field.addClass("default");
      } else {
        if(searchText) {
          this.search_field.val(searchText);
        } else {
          this.search_field.val("");
        }

        return this.search_field.removeClass("default");
      }
    };

    Chosen.prototype.search_results_mouseup = function(evt) {
      var target;
      target = $(evt.target).hasClass("active-result") ? $(evt.target) : $(evt.target).parents(".active-result").first();
      if (target.length) {
        this.result_highlight = target;
        this.result_select(evt);
        return this.search_field.focus();
      }
    };

    Chosen.prototype.search_results_mouseover = function(evt) {
      var target;
      target = $(evt.target).hasClass("active-result") ? $(evt.target) : $(evt.target).parents(".active-result").first();
      if (target) {
        return this.result_do_highlight(target);
      }
    };

    Chosen.prototype.search_results_mouseout = function(evt) {
      if ($(evt.target).hasClass("active-result" || $(evt.target).parents('.active-result').first())) {
        return this.result_clear_highlight();
      }
    };

    Chosen.prototype.choice_build = function(item) {
      var choice, close_link,
        _this = this;
      choice = $('<li />', {
        "class": "search-choice"
      }).html("<span>" + (this.choice_label(item)) + "</span>");
      if (item.disabled) {
        choice.addClass('search-choice-disabled');
      } else {
        close_link = $('<a />', {
          "class": 'search-choice-close',
          'data-option-array-index': item.array_index
        });
        close_link.bind('click.chosen', function(evt) {
          return _this.choice_destroy_link_click(evt);
        });
        choice.append(close_link);
      }
      return this.search_container.before(choice);
    };

    Chosen.prototype.choice_destroy_link_click = function(evt) {
      evt.preventDefault();
      evt.stopPropagation();
      if (!this.is_disabled) {
        return this.choice_destroy($(evt.target));
      }
    };

    Chosen.prototype.choice_destroy = function(link) {
      if (this.result_deselect(link[0].getAttribute("data-option-array-index"))) {
        this.show_search_field_default();
        if (this.is_multiple && this.choices_count() > 0 && this.search_field.val().length < 1) {
          this.results_hide();
        }
        link.parents('li').first().remove();
        return this.search_field_scale();
      }
    };

    Chosen.prototype.results_reset = function() {
      this.reset_single_select_options();
      this.form_field.options[0].selected = true;
      this.single_set_selected_text();
      this.show_search_field_default();
      this.results_reset_cleanup();
      this.form_field_jq.trigger("change");
      if (this.active_field) {
        return this.results_hide();
      }
    };

    Chosen.prototype.results_reset_cleanup = function() {
      this.current_selectedIndex = this.form_field.selectedIndex;
      return this.selected_item.find("abbr").remove();
    };
  // 选中方法
    Chosen.prototype.result_select = function(evt) {
      var high, item;
      if (this.result_highlight) {

        high = this.result_highlight;
        this.result_clear_highlight();
        if (this.is_multiple && this.max_selected_options <= this.choices_count()) {
          this.form_field_jq.trigger("chosen:maxselected", {
            chosen: this
          });
          return false;
        }
        if (this.is_multiple) {
          high.removeClass("active-result");
        } else {
          this.reset_single_select_options();
        }
        high.addClass("result-selected");

        item = this.results_data[high[0].getAttribute("data-option-array-index")];
        item.selected = true;
        this.form_field.options[item.options_index].selected = true;
         // 同步当前选中值

         this.current_value = this.form_field.value;

        this.selected_option_count = null;
        if (this.is_multiple) {
          this.choice_build(item);
        } else {
          this.single_set_selected_text(this.choice_label(item));
        }
        if (!((evt.metaKey || evt.ctrlKey) && this.is_multiple)) {
          this.results_hide();
        }
        if(!this.search_field.val()) {
          this.search_field.val(""); // 存在搜索字符情况下不要删搜索字符
        }

        if (this.is_multiple || this.form_field.selectedIndex !== this.current_selectedIndex) {
          this.form_field_jq.trigger("change", {
            'selected': this.form_field.options[item.options_index].value
          });
        }
        this.current_selectedIndex = this.form_field.selectedIndex;
        evt.preventDefault();
        return this.search_field_scale();
      }
    };

    Chosen.prototype.single_set_selected_text = function(text) {
      if (text == null) {
        text = this.default_text;
      }
      if (text === this.default_text) {
        this.selected_item.addClass("chosen-default");
      } else {
        this.single_deselect_control_build();
        this.selected_item.removeClass("chosen-default");
      }
      return this.selected_item.find("span").html(text);
    };

    Chosen.prototype.result_deselect = function(pos) {
      var result_data;
      result_data = this.results_data[pos];
      if (!this.form_field.options[result_data.options_index].disabled) {
        result_data.selected = false;
        this.form_field.options[result_data.options_index].selected = false;
        this.selected_option_count = null;
        this.result_clear_highlight();
        if (this.results_showing) {
          this.winnow_results();
        }
        this.form_field_jq.trigger("change", {
          deselected: this.form_field.options[result_data.options_index].value
        });
        this.search_field_scale();
        return true;
      } else {
        return false;
      }
    };

    Chosen.prototype.single_deselect_control_build = function() {
      if (!this.allow_single_deselect) {
        return;
      }
      if (!this.selected_item.find("abbr").length) {
        this.selected_item.find("span").first().after("<abbr class=\"search-choice-close\"></abbr>");
      }
      return this.selected_item.addClass("chosen-single-with-deselect");
    };

    Chosen.prototype.get_search_text = function() {
      return $('<div/>').text($.trim(this.search_field.val())).html();
    };

    Chosen.prototype.winnow_results_set_highlight = function() {
      var do_high, selected_results;
      selected_results = !this.is_multiple ? this.search_results.find(".result-selected.active-result") : [];
      do_high = selected_results.length ? selected_results.first() : this.search_results.find(".active-result").first();
      if (do_high != null) {
        return this.result_do_highlight(do_high);
      }
    };

    Chosen.prototype.no_results = function(terms) {
      var no_results_html;
      no_results_html = $('<li class="no-results">' + this.results_none_found + ' "<span></span>"</li>');
      no_results_html.find("span").first().html(terms);
      this.search_results.append(no_results_html);
      return this.form_field_jq.trigger("chosen:no_results", {
        chosen: this
      });
    };

    Chosen.prototype.no_results_clear = function() {
      return this.search_results.find(".no-results").remove();
    };

    Chosen.prototype.keydown_arrow = function() {
      var next_sib;
      if (this.results_showing && this.result_highlight) {
        next_sib = this.result_highlight.nextAll("li.active-result").first();
        if (next_sib) {
          return this.result_do_highlight(next_sib);
        }
      } else {
        return this.results_show();
      }
    };

    Chosen.prototype.keyup_arrow = function() {
      var prev_sibs;
      if (!this.results_showing && !this.is_multiple) {
        return this.results_show();
      } else if (this.result_highlight) {
        prev_sibs = this.result_highlight.prevAll("li.active-result");
        if (prev_sibs.length) {
          return this.result_do_highlight(prev_sibs.first());
        } else {
          if (this.choices_count() > 0) {
            this.results_hide();
          }
          return this.result_clear_highlight();
        }
      }
    };

    Chosen.prototype.keydown_backstroke = function() {
      var next_available_destroy;
      if (this.pending_backstroke) {
        this.choice_destroy(this.pending_backstroke.find("a").first());
        return this.clear_backstroke();
      } else {
        next_available_destroy = this.search_container.siblings("li.search-choice").last();
        if (next_available_destroy.length && !next_available_destroy.hasClass("search-choice-disabled")) {
          this.pending_backstroke = next_available_destroy;
          if (this.single_backstroke_delete) {
            return this.keydown_backstroke();
          } else {
            return this.pending_backstroke.addClass("search-choice-focus");
          }
        }
      }
    };

    Chosen.prototype.clear_backstroke = function() {
      if (this.pending_backstroke) {
        this.pending_backstroke.removeClass("search-choice-focus");
      }
      return this.pending_backstroke = null;
    };

    Chosen.prototype.keydown_checker = function(evt) {
      var stroke, _ref1;
      stroke = (_ref1 = evt.which) != null ? _ref1 : evt.keyCode;
      this.search_field_scale();
      if (stroke !== 8 && this.pending_backstroke) {
        this.clear_backstroke();
      }
      switch (stroke) {
        case 8:
          this.backstroke_length = this.search_field.val().length;
          break;
        case 9:
          if (this.results_showing && !this.is_multiple) {
            this.result_select(evt);
          }
          this.mouse_on_container = false;
          break;
        case 13:
          if (this.results_showing) {
            evt.preventDefault();
          }
          break;
        case 32:
          if (this.disable_search) {
            evt.preventDefault();
          }
          break;
        case 38:
          evt.preventDefault();
          this.keyup_arrow();
          break;
        case 40:
          evt.preventDefault();
          this.keydown_arrow();
          break;
      }
    };

    Chosen.prototype.search_field_scale = function() {
      var div, f_width, h, style, style_block, styles, w, _i, _len;
      if (this.is_multiple) {
        h = 0;
        w = 0;
        style_block = "position:absolute; left: -1000px; top: -1000px; display:none;"; //
        styles = ['font-size', 'font-style', 'font-weight', 'font-family', 'line-height', 'text-transform', 'letter-spacing'];
        for (_i = 0, _len = styles.length; _i < _len; _i++) {
          style = styles[_i];
          style_block += style + ":" + this.search_field.css(style) + ";";
        }
        div = $('<div />', {
          'style': style_block
        });
        div.text(this.search_field.val());
        $('body').append(div);
        w = div.width() + 25;
        div.remove();
        f_width = this.container.outerWidth();
        if (w > f_width - 10) {
          w = f_width - 10;
        }
        return this.search_field.css({
          'width': w + 'px'
        });
      }
    };
    /**
     * 设置 chosen 值
     * 需要在两种情况下设置chosen 的值
     * 运行中 设置值 和初始化设置 值
     * 运行中 设置值 检查 是否和defalutValue一致 不一致 重写并选中
     * 初始化设置值  在new 时候也可以从defalut_value 参数中获取
     * */
    Chosen.prototype.set_value = function (val) {
        this.current_value = val; // || this.current_value;  如果需要判断 则要判断是否为空字符
        //选中功能
        // 如果是远程加载 没有 options 不执行 ！
        if(this.form_field.options.length > 0 ) {
            $(this.form_field).val(val);
            $(this.form_field).trigger("chosen:update");
        }
        if(this.form_field.selectedIndex > 0) {
            // 如果选中 则触发  没选中则不要触发 ！
            $(this.form_field).trigger("change", {
                'selected': val
            });
        }


    }
    Chosen.prototype.get_value = function () {
          return this.current_value;
    }
    /**
     *
     * */
    Chosen.prototype.request  = function (req) {
        this.options.url = req.url || this.options.url;
        this.options.param = req.param || this.options.param;

        var that = this;
        var promise = this.get_data();
        promise.then(function () {
            that.reset_select_options(); //这里 可以清理一下之前创建 遗留的  search context dom 等
            var css_props = that.css_props();
            that.container.attr(css_props);
            that.results_update_field();
          // 暂时注释 request 异步绑定 infinitescroll 的功能
            if(!that.infiniteScroll) {
              //绑定分页功能
              that.infiniteScroll = new InfiniteScroll(that);

            }
          //  that.init(); //这里初始化 要等抽象类执行完毕  后期优化一下 这里先预定 异步完成后执行 预定
        });
        promise.fail(function (e) {
          console.error(e); });
    }

      // add byli 新增远程获取数据方法
    Chosen.prototype.get_data = function() {
          // 适配CMIS 中的查询方法
          var transform = function (d) {
              var ret = [];
              if(typeof d == "object" &&   d.rows instanceof Array ) {
                  ret = d.rows
              } else if( d instanceof Array) {
                  ret = d
              }
              return ret
          }
          // 构造 分页数据
          // httprequest 外部 promise 请求类
          var that = this;
          that.options.pagesize = that.options.pagesize ? that.options.pagesize :30
          var data = { rows :that.options.pagesize };
          // 遮罩功能
          this.showLoadingMore();
          $.extend(data,this.options.param);
          var promise = httpRequest({ url :this.options.url , data : data });
          promise.then(function (d) {
              that.remote_data = transform(d);
              that.hideLoadingMore();
          });
          return promise;
      }


      return Chosen;

  })(AbstractChosen);


  /**
   * 分页滚动
   * 1 提供的功能
   *   1.1滚动到末尾将请求新页数数据
   *   1.2弹出加载中的提示 清除加载中提示
   *   1.3追加到ul list 中的方法
   *   1.4
   * 2 滚动事件监听
   *
   * 创建时机  init 执行完毕   和 load 执行完毕
   */

  //滚动事件监听
  var InfiniteScroll = (function () {
        function InfiniteScroll(chosen) {
          if (!chosen && !(chosen instanceof Chosen)) return console.warn(chosen, "对象不符合要求无法添加滚动事件");
          this.chosen = chosen;
          this.chosen_results = this.chosen.container.find(".chosen-results"); // HTML ul list
          this.isloading = false;
          this.currentPage = 1;
          this.isEnd = false;
          this.total = 0;
          this.totalPage = 0;
          this.bind();
        }
        InfiniteScroll.prototype.bind = function () {
          var that = this;
          var timer;
          var onscroll = function (e) {
              if(e.target.scrollTop +  e.target.clientHeight >=  e.target.scrollHeight) {
                // 滚动到了底部
                if(!this.isloading) {
                    // if(timer) {
                    //     clearTimeout(timer);
                    //     timer = null;
                    // }
                    // timer = setTimeout(function () {
                    //      // that.showLoadingMore();
                        var searchText = that.chosen.get_search_text();
                        if(!searchText) {
                          that.request();
                        } else { console.log("存在搜索关键字不请求") }

                    // },400);
                }
              }
           }
           this.chosen.container.find(".chosen-results").bind("scroll",onscroll);
           return this;
        };
        // InfiniteScroll.prototype.showLoadingMore = function () {
        //     if(!this.isloading) {
        //         var $more = $("<div class='chosen-moreloading' />");
        //         var $chosendrop = this.chosen.container.find(".chosen-drop");
        //         $chosendrop.prepend($more);
        //     }
        //     this.isloading = true;
        // };
        // InfiniteScroll.prototype.hideLoadingMore = function () {
        //   this.chosen.container.find(".chosen-moreloading").remove();
        //   this.isloading = false;
        // };
        InfiniteScroll.prototype.setPage = function (page) {
          this.currentPage = page;
          if(this.chosen.options.param) {
            this.chosen.options.param.page = page;
          } else {
            this.chosen.options.param = { page : page };
          }
        }
        InfiniteScroll.prototype.countPage = function () {
            if( this.total < 0 ) return this.totalPage = 0;
            var pagesize =  this.chosen.options.pagesize;
            var totalPage = this.total;
            this.totalPage = totalPage % pagesize == 0 ? totalPage / pagesize : Math.ceil(totalPage /pagesize);
        }

        InfiniteScroll.prototype.request = function () {
            if(this.totalPage != 0) {
               // 进行最后一页检查
                if( this.currentPage > this.totalPage) {
                  //this.hideLoadingMore();  最后一页
                  return null;
                }
            }

           // this.currentPage++; // isEnd 可以再第一次判断 就通过 countpage number 计算出来
           // this.chosen.options.param.page = this.currentPage; //这里是请求 发出去的携带的 page 属性 CMIS 后台适配的参数 可以不用前台传入

            this.setPage(++this.currentPage);
            this.cache_data = this.chosen.remote_data || []; // 缓存之前的请求数据  //必须是数组类型
            var promise = this.chosen.get_data();
            var that= this;
            var cacheIndex = this.cache_data.length  ; // - rows

            promise.then(function (d) {
                // console.log(d);
                that.total =  d.total;
                that.countPage();

                if(that.chosen.remote_data < 1) {
                    that.isEnd = true;
                }
                that.cache_data =  that.cache_data.concat(that.chosen.remote_data);
                that.chosen.remote_data = that.cache_data;
                // console.log(that.chosen.remote_data.length,that.chosen.remote_data)
                that.chosen.reset_select_options(true); //这里 可以清理一下之前创建 遗留的  search context dom 等
                //that.chosen.results_update_field(); // 更新新的 select 选项到 ul  中
                // that.chosen.set_default_text();
                // if (!that.is_multiple) { // 暂 不用多选
                //     this.results_reset_cleanup();
                // }
                // this.result_clear_highlight();
                // console.log(that.chosen.result_highlight);

                that.chosen.results_build(true); //这里 search_math 为 undefine 导致返回的 context 为空 并不能成功 组装和映射 ul li  唯一的作用是 重写 that.chosen.results_data
                // that.chosen.results_data = SelectParser.select_to_array(that.chosen.form_field);
                that.chosen.winnow_results(); //构造新的 ulli 准备数据

                // 选中之前 ul 中 li
                // 滚动到之前的 li 位置

                var findLast = that.chosen_results.find("li[data-option-array-index='" + cacheIndex + "']");
                // console.log("offsetTop:"+ findLast[0].offsetTop + "   scrolltop:" + findLast[0].scrollTop);
                // console.log(findLast.html());
                that.chosen.result_do_highlight(findLast);

                that.chosen.result_highlight = findLast;
                that.chosen.result_highlight.addClass("highlighted");
                var high_top = that.chosen.result_highlight.position().top + that.chosen.search_results.scrollTop();
                that.chosen.search_results.scrollTop(high_top);

               // that.hideLoadingMore();
                    // maxHeight = parseInt(this.search_results.css("maxHeight"), 10);
                    // visible_top = this.search_results.scrollTop();
                    // visible_bottom = maxHeight + visible_top;
                    // high_top = this.result_highlight.position().top + this.search_results.scrollTop();
                    // high_bottom = high_top + this.result_highlight.outerHeight();
                    // if (high_bottom >= visible_bottom) {
                    //     return this.search_results.scrollTop((high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);
                    // } else if (high_top < visible_top) {
                    //     return
                    // }

                // that.scrollTo(  findLast[0].offsetTop);
                // if (that.results_showing) {
                //     return that.winnow_results();
                // }

            //  that.init(); //这里初始化 要等抽象类执行完毕  后期优化一下 这里先预定 异步完成后执行 预定
            }).fail(function(err) {
                console.error(err)})
            return promise;
        }
        InfiniteScroll.prototype.scrollTo = function (offsetTop) {
            if(!offsetTop) return;
            this.chosen_results.animate({ scrollTop: offsetTop }, 1000);
        }
        InfiniteScroll.prototype.unbind = function () {
          $( "#foo").unbind( "click" );
          this.chosen.container.find(".chosen-results").unbind("scroll");
          this.setPage(1);
        }
        return InfiniteScroll;
  })();


}).call(this);
